services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yii2-php
    volumes:
      - ./web:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/yii2/db.php:/var/www/html/config/db.php
      - ./docker/yii2/params.php:/var/www/html/config/params.php
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: yii2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT}
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
